#!/usr/bin/env python3
"""Generate the placeholder brand icon.

    python tools/make_icon.py

Writes `icon.svg` and renders every PNG size from it. The SVG is build output — change
this script and re-run it, never edit the SVG by hand, or the next run silently reverts
your edit.

This draws a deliberately anonymous chip glyph. It exists so a new repository's HACS job
passes on day one; replace it with something that says what the device is.
"""

from __future__ import annotations

import math
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: The artboard. Home Assistant only ever serves the 256 and 512 renders, but the source
#: is drawn at 1024 so the maths below is in round numbers.
SIZE = 1024

#: Superellipse exponent. Around 5 the curvature eases into the straight edges instead of
#: meeting them at a tangent the way a rounded rectangle's circular arcs do — the
#: difference between an iOS app icon and a CSS `border-radius`.
SQUIRCLE_N = 5.0


def squircle(size: float, n: float = SQUIRCLE_N, steps: int = 720) -> str:
    """Return an iOS-style superellipse as an SVG path, inscribed in a `size` square."""
    r = size / 2
    points = []
    for i in range(steps):
        t = 2 * math.pi * i / steps
        cos_t, sin_t = math.cos(t), math.sin(t)
        x = math.copysign(abs(cos_t) ** (2 / n), cos_t)
        y = math.copysign(abs(sin_t) ** (2 / n), sin_t)
        points.append((r + x * r, r + y * r))
    head = f"M{points[0][0]:.2f},{points[0][1]:.2f}"
    return head + "".join(f"L{x:.2f},{y:.2f}" for x, y in points[1:]) + "Z"


def build() -> str:
    """Return the SVG source."""
    return f"""\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" \
width="{SIZE}" height="{SIZE}">
  <title>Placeholder integration icon</title>

  <!-- Generated by tools/make_icon.py. Do not edit; re-run the script. -->

  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#3B4250"/>
      <stop offset="1" stop-color="#23272F"/>
    </linearGradient>
  </defs>

  <path d="{squircle(SIZE)}" fill="url(#tile)"/>

  <g fill="none" stroke="#41BDF5" stroke-width="44" stroke-linecap="round">
    <rect x="336" y="336" width="352" height="352" rx="72"/>
    <g stroke-linecap="butt">
      <path d="M424 336V248M512 336V248M600 336V248"/>
      <path d="M424 688v88M512 688v88M600 688v88"/>
      <path d="M336 424H248M336 512H248M336 600H248"/>
      <path d="M688 424h88M688 512h88M688 600h88"/>
    </g>
  </g>

  <circle cx="{SIZE // 2}" cy="{SIZE // 2}" r="60" fill="#41BDF5"/>
</svg>
"""


def main() -> None:
    """Write the SVG and render the PNGs beside it."""
    (component,) = (ROOT / "custom_components").iterdir()
    source = component / "brand" / "icon.svg"
    source.write_text(build())
    print(f"{source}")

    subprocess.run(
        [sys.executable, str(ROOT / "tools" / "render_brand.py"), str(source)],
        check=True,
    )


if __name__ == "__main__":
    main()
